<a href="https://colab.research.google.com/github/GunaSamhith/ML-labActivity/blob/main/9_6_2_KnearestNeighbour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = pd.DataFrame({
    'Brightness': [40, 50, 60, 10, 70, 60, 25],
    'Saturation': [20, 50, 90, 25, 70, 10, 80],
    'Class': ['Red', 'Blue', 'Blue', 'Red',
              'Blue', 'Red', 'Blue']
})

display(data)

   Brightness  Saturation Class
0          40          20   Red
1          50          50  Blue
2          60          90  Blue
3          10          25   Red
4          70          70  Blue
5          60          10   Red
6          25          80  Blue

In [ ]:
new_brightness = 45
new_saturation = 40

In [ ]:
import math

data['Distance'] = data.apply(
    lambda row: math.sqrt(
        (row['Brightness'] - new_brightness) ** 2 +
        (row['Saturation'] - new_saturation) ** 2
    ),
    axis=1
)

print("Distances from new point:")
display(data.sort_values('Distance'))

Distances from new point:

   Brightness  Saturation Class   Distance
1          50          50  Blue  11.180340
0          40          20   Red  20.615528
5          60          10   Red  33.541020
3          10          25   Red  38.078866
4          70          70  Blue  39.051248
6          25          80  Blue  44.721360
2          60          90  Blue  52.201533

In [ ]:
k = 3

nearest = data.sort_values(
    'Distance'
).head(k)

print("Nearest Neighbors:")
display(nearest)

Nearest Neighbors:

   Brightness  Saturation Class   Distance
1          50          50  Blue  11.180340
0          40          20   Red  20.615528
5          60          10   Red  33.541020

In [ ]:
prediction = nearest['Class'].mode()[0]

print("New Entry:")
print("Brightness:", new_brightness)
print("Saturation:", new_saturation)

print("\nPredicted Class:", prediction)

New Entry:
Brightness: 45
Saturation: 40

Predicted Class: Red

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

X = data[['Brightness', 'Saturation']]
y = data['Class']

model = KNeighborsClassifier(
    n_neighbors=3,
    metric='minkowski',
    p=2
)

model.fit(X, y)

new_point = [[45, 40]]

prediction = model.predict(new_point)

print("Predicted Class:", prediction[0])

Predicted Class: Red

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [ ]:
new_point = pd.DataFrame({
    'Brightness': [45],
    'Saturation': [40]
})

prediction = model.predict(new_point)

print("Predicted Class:", prediction[0])

Predicted Class: Red